### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mihirg008**
Added a few emoticons, gifs and badges to make it look more attractive

### CODE REVIEW

**Comment by Parth-Vader** [comment]
Why is `kinda SFW` required? 
Also, I wanted the working of moboff to be displayed in a GIF - see this for example : [keep](https://raw.githubusercontent.com/OrkoHunter/keep/master/data/keep.gif).

**Comment by mihirg008** [comment]
kinda SFW made it look a bit humorous :P 
and the running moboff thing....there is a problem in that...
moboff also asks the directory when i am using my mobile as device. So it first downloads in my laptop then to the device so that will also be shown.

**Comment by Parth-Vader** [comment]
@mihirg008 I think `kinda SFW` should be removed, and the GIFs depicting the usage need to be here.

**Comment by mihirg008** [comment]
I'll do that ASAP.

**Pull request closed without merging**
