### PR TITLE
Enabled command to run from anywhere in the system

### LINKED ISSUE #11: Enable command to run from anywhere in the system
Currently, you need to be inside the MobOff folder to run the command successfully, the path needs to be made universal instead of relative.

### PR DESCRIPTION
**Pull request by Ilozuluchris**
fixes #11

### CODE REVIEW

**Comment by Parth-Vader** [comment]
This change makes it possible to call the mainscript.py file from anywhere, but the way it is written, also requires absolute path for `file.txt` and the music folder. This needs to be added before merging.

**Comment by Ilozuluchris** [comment]
I do not quite understand , you could you give an example,may be that would help.

**Comment by Parth-Vader** [comment]
[Accessing `file.txt`](https://github.com/Parth-Vader/MobOff/blob/master/mainscript.py#L49 ) and the [Music folder](https://github.com/Parth-Vader/MobOff/blob/master/mainscript.py#L62) can be done only from `MobOff` folder as of now. The file paths need to be made absolute so that it can be accessed from anywhere in the system.
Do you get my point? :)

**Comment by Ilozuluchris** [comment]
Yeah I do

**Comment by Parth-Vader** [comment]
Thanks a lot @Ilozuluchris. Merging.

**Comment by Ilozuluchris** [comment]
Thanks @Parth-Vader  Happy Hacktoberfest

**Pull request merged**
