### PR TITLE
Update READMe

### PR DESCRIPTION
**Pull request by HariMahi**

### CODE REVIEW

**Comment by HariMahi** [comment]
changes in README are not seen in the main repository

**Comment by Parth-Vader** [comment]
@HariMahi The badges are not looking good, I'm afraid. Can you remove them and add a working GIF for the repo instead? :smile:

**Comment by HariMahi** [comment]
Kk i will try
But i have seen these batches on many similar projects

**Comment by Parth-Vader** [comment]
You can keep the `made with python` badge on the top.

**Comment by HariMahi** [comment]
Review the changes, and explain me what kind of GIF do you like to have.

**Comment by yash98** [comment]
I think he meant to have something like [here](https://raw.githubusercontent.com/OrkoHunter/keep/master/data/keep.gif) or in this [README.md](https://github.com/Parth-Vader/FB-Spider/blob/master/README.md)

**Pull request closed without merging**
