### PR TITLE
ask for directory

### PR DESCRIPTION
**Pull request by elias174**
I've use tkinter for ask directory, i was thinking in urwid or ncurses, but maybe won't work in windows.

### CODE REVIEW

**Comment by Parth-Vader** [comment]
Hi, please `git pull` and resend the PR.

**Comment by elias174** [comment]
@Parth-Vader i updated my pull request. please review

**Comment by Parth-Vader** [comment]
@elias174 Thanks a lot for adding it with tkinter. 

One more change is need : adding `tkinter` installation instruction in README file.

Also since it is `Tkinter` for `python2` and `tkinter` for `python3`, something like

```
try:
    from Tkinter import *
except ImportError:
    from tkinter import *
```
would also be required.

**Comment by elias174** [comment]
@Parth-Vader i added the compatibility for python2 and python3

**Comment by Parth-Vader** [comment]
@elias174 Hi, sorry for the delay in replying.
I just made some changes to the program, can you please refactor your code according to it?

Thanks.

**Pull request closed without merging**
